version: '2'
services:
  db:
    image: mysql
    user: "1000"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: upzone
      MYSQL_DATABASE: rpgtables
      MYSQL_USER: upzone
      MYSQL_PASSWORD: upzone
    expose:
      - '3306'
    ports:
      - 3306:3306
  php:
    build: php7-apache
    volumes:
      - ./code:/var/www/app
    ports:
      - 80:80
      - 9001:9001
